#
# Copyright (C) 2020 Android Ice Cold Project
#
# SPDX-License-Identifier: Apache-2.0
#

# Init (Android project name autogenerated by vendor_buildinfo.sh as a system.prop)
PRODUCT_PROPERTY_OVERRIDES += \
    ro.boot.project_name=19801 \
    ro.vendor.boot.project_name=19801

# build properties
PRODUCT_PROPERTY_OVERRIDES += \
    persist.sys.oem.region=OverSeas \
    ro.product.device=hotdog \
    ro.vendor.build.real.device=true \
    vendor.product.device=hotdog \
    vendor.product.manufacturer=OPD

